---
- name: Create {{ install_dir }}
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: directory
    group: "{{ mc_user }}"
    owner: "{{ mc_user }}"
    mode: '0755'

- name: Get Minecraft JAR
  ansible.builtin.get_url:

    url: "{{ minecraft_server_url }}"
    dest: "{{ install_dir }}/minecraft_server-{{ minecraft_version }}.jar"
    mode: '0644'

- name: Accept Minecraft EULA
  ansible.builtin.lineinfile:
    path: "{{ install_dir }}/eula.txt"
    line: eula=true
    state: present
    create: true
    mode: '0644'

- name: Configure server properties
  ansible.builtin.template:
    src: server.properties.j2
    dest: "{{ install_dir }}/server.properties"
    mode: '0644'
  notify: restart supervisor
