on:
  workflow_dispatch:
    inputs:
      version_to_publish:
        description: What version tag to publish to ansible galaxy
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: galaxy
        uses: ome/action-ansible-galaxy-publish@main
        with:
          galaxy-api-key: ${{ secrets.GALAXY_API_KEY }}
          galaxy-version: ${{  github.events.inputs.version_to_publish }}
          role-name: ${{ steps.role-name.outputs.rolename }}
