name: Publish to Ansible galaxy

on:
  workflow_dispatch:
    inputs:
      branch_to_publish:
        description: What branch to publish
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Show version
        run: echo ${{ github.events.inputs.branch_to_publish }}
      - name: galaxy
        uses: ome/action-ansible-galaxy-publish@main
        with:
          galaxy-api-key: ${{ secrets.GALAXY_API_KEY }}
          galaxy-version: ${{ inputs.version_to_publish }}
          role-name: minecraft
